// <auto-generated />
using EmojiVoto.EmojiSvc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmojiVoto.EmojiSvc.Persistence.Migrations
{
    [DbContext(typeof(EmojiDbContext))]
    [Migration("20230115212204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("EmojiVoto.EmojiSvc.Domain.Emoji", b =>
                {
                    b.Property<string>("Shortcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unicode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Shortcode");

                    b.ToTable("Emojies");
                });
#pragma warning restore 612, 618
        }
    }
}
